// <auto-generated />
namespace WebTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update13));
        
        string IMigrationMetadata.Id
        {
            get { return "202412231427270_Update13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
